version: "3.9"
services:
  balancer:
    image: nginx:1.25.5-alpine3.19
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      default:
        aliases:
          - www.dev.jtspike.com
          - api.dev.jtspike.com
  
  postgres:
    image: postgres:16.2-alpine3.18
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  www:
    build:
      context: "./www"
    volumes:
      - ./www/package-lock.json:/code/package-lock.json
      - ./www/package.json:/code/package.json
      - ./www/src:/code/src

  api:
    build:
      context: "./api"
    volumes:
      - ./api/bin:/code/bin
      - ./api/package-lock.json:/code/package-lock.json
      - ./api/package.json:/code/package.json
      - ./api/src:/code/src
    environment:
      VERSION: 'development'
      WATCH: 1

volumes:
  postgres-data:
