version: "3.9"
services:
  balancer:
    image: nginx:1.25.5-alpine3.19
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf
      - ./src/fullchain.pem:/etc/ssl/private/fullchain.pem
      - ./src/privkey.pem:/etc/ssl/private/privkey.pem
    networks:
      default:
        aliases:
          - www.dev.jtspike.com
          - api.dev.jtspike.com
  
  postgres:
    image: postgres:16.2-alpine3.18
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - pgsql:/var/lib/postgresql/data

  www:
    build:
      context: "../www"
    volumes:
      - ../www/bin:/code/bin
      - ../www/cogs.js:/code/cogs.js
      - ../www/package-lock.json:/code/package-lock.json
      - ../www/package.json:/code/package.json
      - ../www/src:/code/src
    environment:
      API_URL: 'https://api.dev.jtspike.com'
      VERSION: 'development'
      WATCH: 1

  api:
    build:
      context: "../api"
    volumes:
      - ../api/bin:/code/bin
      - ../api/package-lock.json:/code/package-lock.json
      - ../api/package.json:/code/package.json
      - ../api/src:/code/src
    environment:
      POSTGRES_CONNECTION_STRING: 'pg://postgres:postgres@postgres/spike'
      POSTGRES_DATABASE_NAME: 'spike'
      VERSION: 'development'
      WATCH: 1

volumes:
  pgsql:
