app = 'jtspike-api'
primary_region = 'dfw'

[deploy]
  strategy = 'bluegreen'

[env]
  ALLOWED_EMAIL_DOMAINS = 'jobtread.com'
  APP_URL = 'https://www.jtspike.com'
  VERSION = 'production'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[checks]
  [checks.alive]
    port = 80
    type = 'http'
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'
    method = 'get'
    path = '/version'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
