name: Fly Deploy API
on:
  push:
    paths:
      - api/**
    branches:
      - main
jobs:
  deploy:
    name: Deploy api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd api && flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
